import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

sns.set(style='dark')

aothizhongxin_year = pd.read_csv("./dashboard/aothizhongxin_year.csv", header=[0, 1])
aothizhongxin_month = pd.read_csv("./dashboard/aothizhongxin_month.csv", header=[0, 1])
changping_year = pd.read_csv("./dashboard/changping_year.csv", header=[0, 1])
changping_month = pd.read_csv("./dashboard/changping_month.csv", header=[0, 1])
dingling_year = pd.read_csv("./dashboard/dingling_year.csv", header=[0, 1])
dingling_month = pd.read_csv("./dashboard/dingling_month.csv", header=[0, 1])
dongsi_year = pd.read_csv("./dashboard/dongsi_year.csv", header=[0, 1])
dongsi_month = pd.read_csv("./dashboard/dongsi_month.csv", header=[0, 1])
guanyuan_year = pd.read_csv("./dashboard/guanyuan_year.csv", header=[0, 1])
guanyuan_month = pd.read_csv("./dashboard/guanyuan_month.csv", header=[0, 1])
gucheng_year = pd.read_csv("./dashboard/gucheng_year.csv", header=[0, 1])
gucheng_month = pd.read_csv("./dashboard/gucheng_month.csv", header=[0, 1])
huairou_year = pd.read_csv("./dashboard/huairou_year.csv", header=[0, 1])
huairou_month = pd.read_csv("./dashboard/huairou_month.csv", header=[0, 1])
nongzhanguan_year = pd.read_csv("./dashboard/nongzhanguan_year.csv", header=[0, 1])
nongzhanguan_month = pd.read_csv("./dashboard/nongzhanguan_month.csv", header=[0, 1])
shunyi_year = pd.read_csv("./dashboard/shunyi_year.csv", header=[0, 1])
shunyi_month = pd.read_csv("./dashboard/shunyi_month.csv", header=[0, 1])
tiantan_year = pd.read_csv("./dashboard/tiantan_year.csv", header=[0, 1])
tiantan_month = pd.read_csv("./dashboard/tiantan_month.csv", header=[0, 1])
wanliu_year = pd.read_csv("./dashboard/wanliu_year.csv", header=[0, 1])
wanliu_month = pd.read_csv("./dashboard/wanliu_month.csv", header=[0, 1])
wanshouxigong_year = pd.read_csv("./dashboard/wanshouxigong_year.csv", header=[0, 1])
wanshouxigong_month = pd.read_csv("./dashboard/wanshouxigong_month.csv", header=[0, 1])

st.title('Grafik Konsentrasi PM2.5 dan PM10 Pada Tiap Tahun & Bulan')
st.subheader('Aothizhongxin')
fig1, ax1 = plt.subplots(figsize=(10, 6))
year = aothizhongxin_year.index
ax1.plot(year, aothizhongxin_year[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax1.plot(year, aothizhongxin_year[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax1.plot(year, aothizhongxin_year[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax1.plot(year, aothizhongxin_year[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax1.set_title('Aothizhongxin Yearly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax1.set_xlabel('Year', fontsize=14)
ax1.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax1.tick_params(axis='x', labelsize=12)
ax1.tick_params(axis='y', labelsize=12)
ax1.legend(fontsize=12)
st.pyplot(fig1)

fig2, ax2 = plt.subplots(figsize=(10, 6))
month = aothizhongxin_month.index
ax2.plot(month, aothizhongxin_month[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax2.plot(month, aothizhongxin_month[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax2.plot(month, aothizhongxin_month[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax2.plot(month, aothizhongxin_month[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax2.set_title('Aothizhongxin Monthly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax2.set_xlabel('Month', fontsize=14)
ax2.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax2.tick_params(axis='x', labelsize=12)
ax2.tick_params(axis='y', labelsize=12)
ax2.legend(fontsize=12)
st.pyplot(fig2)

st.subheader('Changping')
fig3, ax3 = plt.subplots(figsize=(10, 6))
year = changping_year.index
ax3.plot(year, changping_year[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax3.plot(year, changping_year[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax3.plot(year, changping_year[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax3.plot(year, changping_year[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax3.set_title('Changping Yearly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax3.set_xlabel('Year', fontsize=14)
ax3.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax3.tick_params(axis='x', labelsize=12)
ax3.tick_params(axis='y', labelsize=12)
ax3.legend(fontsize=12)
st.pyplot(fig3)

fig4, ax4 = plt.subplots(figsize=(10, 6))
month = changping_month.index
ax4.plot(month, changping_month[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax4.plot(month, changping_month[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax4.plot(month, changping_month[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax4.plot(month, changping_month[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax4.set_title('Changping Monthly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax4.set_xlabel('Month', fontsize=14)
ax4.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax4.tick_params(axis='x', labelsize=12)
ax4.tick_params(axis='y', labelsize=12)
ax4.legend(fontsize=12)
st.pyplot(fig4)

st.subheader('Dingling')
fig5, ax5 = plt.subplots(figsize=(10, 6))
year = dingling_year.index
ax5.plot(year, dingling_year[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax5.plot(year, dingling_year[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax5.plot(year, dingling_year[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax5.plot(year, dingling_year[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax5.set_title('Dingling Yearly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax5.set_xlabel('Year', fontsize=14)
ax5.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax5.tick_params(axis='x', labelsize=12)
ax5.tick_params(axis='y', labelsize=12)
ax5.legend(fontsize=12)
st.pyplot(fig5)

fig6, ax6 = plt.subplots(figsize=(10, 6))
month = dingling_month.index
ax6.plot(month, dingling_month[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax6.plot(month, dingling_month[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax6.plot(month, dingling_month[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax6.plot(month, dingling_month[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax6.set_title('Dingling Monthly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax6.set_xlabel('Month', fontsize=14)
ax6.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax6.tick_params(axis='x', labelsize=12)
ax6.tick_params(axis='y', labelsize=12)
ax6.legend(fontsize=12)
st.pyplot(fig6)

st.subheader('Dongsi')
fig7, ax7 = plt.subplots(figsize=(10, 6))
year = dongsi_year.index
ax7.plot(year, dongsi_year[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax7.plot(year, dongsi_year[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax7.plot(year, dongsi_year[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax7.plot(year, dongsi_year[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax7.set_title('Dongsi Yearly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax7.set_xlabel('Year', fontsize=14)
ax7.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax7.tick_params(axis='x', labelsize=12)
ax7.tick_params(axis='y', labelsize=12)
ax7.legend(fontsize=12)
st.pyplot(fig7)

fig8, ax8 = plt.subplots(figsize=(10, 6))
month = dongsi_month.index
ax8.plot(month, dongsi_month[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax8.plot(month, dongsi_month[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax8.plot(month, dongsi_month[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax8.plot(month, dongsi_month[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax8.set_title('Dongsi Monthly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax8.set_xlabel('Month', fontsize=14)
ax8.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax8.tick_params(axis='x', labelsize=12)
ax8.tick_params(axis='y', labelsize=12)
ax8.legend(fontsize=12)
st.pyplot(fig8)

st.subheader('Guanyuan')
fig9, ax9 = plt.subplots(figsize=(10, 6))
year = guanyuan_year.index
ax9.plot(year, guanyuan_year[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax9.plot(year, guanyuan_year[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax9.plot(year, guanyuan_year[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax9.plot(year, guanyuan_year[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax9.set_title('Guanyuan Yearly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax9.set_xlabel('Year', fontsize=14)
ax9.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax9.tick_params(axis='x', labelsize=12)
ax9.tick_params(axis='y', labelsize=12)
ax9.legend(fontsize=12)
st.pyplot(fig9)

fig10, ax10 = plt.subplots(figsize=(10, 6))
month = guanyuan_month.index
ax10.plot(month, guanyuan_month[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax10.plot(month, guanyuan_month[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax10.plot(month, guanyuan_month[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax10.plot(month, guanyuan_month[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax10.set_title('Guanyuan Monthly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax10.set_xlabel('Month', fontsize=14)
ax10.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax10.tick_params(axis='x', labelsize=12)
ax10.tick_params(axis='y', labelsize=12)
ax10.legend(fontsize=12)
st.pyplot(fig10)

st.subheader('Gucheng')
fig11, ax11 = plt.subplots(figsize=(10, 6))
year = gucheng_year.index
ax11.plot(year, gucheng_year[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax11.plot(year, gucheng_year[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax11.plot(year, gucheng_year[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax11.plot(year, gucheng_year[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax11.set_title('Gucheng Yearly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax11.set_xlabel('Year', fontsize=14)
ax11.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax11.tick_params(axis='x', labelsize=12)
ax11.tick_params(axis='y', labelsize=12)
ax11.legend(fontsize=12)
st.pyplot(fig11)

fig12, ax12 = plt.subplots(figsize=(10, 6))
month = gucheng_month.index
ax12.plot(month, gucheng_month[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax12.plot(month, gucheng_month[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax12.plot(month, gucheng_month[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax12.plot(month, gucheng_month[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax12.set_title('Gucheng Monthly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax12.set_xlabel('Month', fontsize=14)
ax12.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax12.tick_params(axis='x', labelsize=12)
ax12.tick_params(axis='y', labelsize=12)
ax12.legend(fontsize=12)
st.pyplot(fig12)

st.subheader('Huairou')
fig10, ax10 = plt.subplots(figsize=(10, 6))
year = huairou_year.index
ax10.plot(year, huairou_year[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax10.plot(year, huairou_year[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax10.plot(year, huairou_year[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax10.plot(year, huairou_year[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax10.set_title('Hairou Yearly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax10.set_xlabel('Year', fontsize=14)
ax10.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax10.tick_params(axis='x', labelsize=12)
ax10.tick_params(axis='y', labelsize=12)
ax10.legend(fontsize=12)
st.pyplot(fig10)

fig11, ax11 = plt.subplots(figsize=(10, 6))
month = huairou_month.index
ax11.plot(month, huairou_month[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax11.plot(month, huairou_month[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax11.plot(month, huairou_month[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax11.plot(month, huairou_month[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax11.set_title('Huairou Monthly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax11.set_xlabel('Month', fontsize=14)
ax11.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax11.tick_params(axis='x', labelsize=12)
ax11.tick_params(axis='y', labelsize=12)
ax11.legend(fontsize=12)
st.pyplot(fig11)

st.subheader('Nongzhanguan')
fig12, ax12 = plt.subplots(figsize=(10, 6))
year = nongzhanguan_year.index
ax12.plot(year, nongzhanguan_year[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax12.plot(year, nongzhanguan_year[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax12.plot(year, nongzhanguan_year[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax12.plot(year, nongzhanguan_year[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax12.set_title('Nongzhanguan Yearly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax12.set_xlabel('Year', fontsize=14)
ax12.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax12.tick_params(axis='x', labelsize=12)
ax12.tick_params(axis='y', labelsize=12)
ax12.legend(fontsize=12)
st.pyplot(fig12)

fig13, ax13 = plt.subplots(figsize=(10, 6))
month = nongzhanguan_month.index
ax13.plot(month, nongzhanguan_month[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax13.plot(month, nongzhanguan_month[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax13.plot(month, nongzhanguan_month[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax13.plot(month, nongzhanguan_month[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax13.set_title('Nongzhanguan Monthly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax13.set_xlabel('Month', fontsize=14)
ax13.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax13.tick_params(axis='x', labelsize=12)
ax13.tick_params(axis='y', labelsize=12)
ax13.legend(fontsize=12)
st.pyplot(fig13)

st.subheader('Shunyi')
fig14, ax14 = plt.subplots(figsize=(10, 6))
year = shunyi_year.index
ax14.plot(year, shunyi_year[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax14.plot(year, shunyi_year[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax14.plot(year, shunyi_year[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax14.plot(year, shunyi_year[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax14.set_title('Shunyi Yearly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax14.set_xlabel('Year', fontsize=14)
ax14.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax14.tick_params(axis='x', labelsize=12)
ax14.tick_params(axis='y', labelsize=12)
ax14.legend(fontsize=12)
st.pyplot(fig14)

fig15, ax15 = plt.subplots(figsize=(10, 6))
month = shunyi_month.index
ax15.plot(month, shunyi_month[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax15.plot(month, shunyi_month[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax15.plot(month, shunyi_month[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax15.plot(month, shunyi_month[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax15.set_title('Shunyi Monthly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax15.set_xlabel('Month', fontsize=14)
ax15.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax15.tick_params(axis='x', labelsize=12)
ax15.tick_params(axis='y', labelsize=12)
ax15.legend(fontsize=12)
st.pyplot(fig15)

st.subheader('Wanliu')
fig18, ax18 = plt.subplots(figsize=(10, 6))
year = wanliu_year.index
ax18.plot(year, wanliu_year[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax18.plot(year, wanliu_year[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax18.plot(year, wanliu_year[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax18.plot(year, wanliu_year[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax18.set_title('Wanliu Yearly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax18.set_xlabel('Year', fontsize=14)
ax18.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax18.tick_params(axis='x', labelsize=12)
ax18.tick_params(axis='y', labelsize=12)
ax18.legend(fontsize=12)
st.pyplot(fig18)

fig19, ax19 = plt.subplots(figsize=(10, 6))
month = wanliu_month.index
ax19.plot(month, wanliu_month[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax19.plot(month, wanliu_month[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax19.plot(month, wanliu_month[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax19.plot(month, wanliu_month[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax19.set_title('Wanliu Monthly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax19.set_xlabel('Month', fontsize=14)
ax19.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax19.tick_params(axis='x', labelsize=12)
ax19.tick_params(axis='y', labelsize=12)
ax19.legend(fontsize=12)
st.pyplot(fig19)

st.subheader('Wanshouxigong')
fig20, ax20 = plt.subplots(figsize=(10, 6))
year = wanshouxigong_year.index
ax20.plot(year, wanshouxigong_year[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax20.plot(year, wanshouxigong_year[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax20.plot(year, wanshouxigong_year[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax20.plot(year, wanshouxigong_year[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax20.set_title('Wanshouxigong Yearly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax20.set_xlabel('Year', fontsize=14)
ax20.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax20.tick_params(axis='x', labelsize=12)
ax20.tick_params(axis='y', labelsize=12)
ax20.legend(fontsize=12)
st.pyplot(fig20)

fig21, ax21 = plt.subplots(figsize=(10, 6))
month = wanshouxigong_month.index
ax21.plot(month, wanshouxigong_month[('PM2.5', 'mean')], label='PM2.5 Mean', marker='o', linewidth=2)
ax21.plot(month, wanshouxigong_month[('PM2.5', 'max')], label='PM2.5 Max', marker='x', linewidth=2)
ax21.plot(month, wanshouxigong_month[('PM10', 'mean')], label='PM10 Mean', marker='o', linewidth=2)
ax21.plot(month, wanshouxigong_month[('PM10', 'max')], label='PM10 Max', marker='x', linewidth=2)
ax21.set_title('Wanshouxigong Monthly PM2.5 and PM10 Levels', fontsize=18, weight='bold')
ax21.set_xlabel('Month', fontsize=14)
ax21.set_ylabel('Concentration (µg/m³)', fontsize=14)
ax21.tick_params(axis='x', labelsize=12)
ax21.tick_params(axis='y', labelsize=12)
ax21.legend(fontsize=12)
st.pyplot(fig21)

